### ISSUE TITLE
Wrong number of columns in line 1. Expected 75, found 4

### ISSUE THREAD

**Issue by Jinny-Wang** [myudelson/hmm-scalable#1]
When I was trying to run the example:
"./trainhmm -s 1.1 -m 1 -p 1 toy_data.txt model.txt predict.txt"
I got the following error:
"trainhmm starting...
Wrong number of columns in line 1. Expected 75, found 4"

Any idea why this happened?

**Comment by myudelson** [comment]
Jingyu,

This is odd. 75 columns is definitely an error. Are you using the supplied toy data file? I’m assuming you do. 
I’ll look into it when I’m back from a trip this week. I have no access to a computer now. 

Best,
Michael 

--
Michael Yudelson
Project Scientist
Carnegie Mellon University
