### ISSUE TITLE
facing issues on running 

### ISSUE THREAD

**Issue by manirds** [myudelson/hmm-scalable#5]
@myudelson  hope you are doing well.

I have cloned the repo to my local, however I am unable to run it as it's throwing  error. please help

 hmm-scalable % ./trainhmm -s 1.1 -m 1 -p 1 toy_data.txt model.txt predict.txt

error :
zsh: no such file or directory: ./trainhmm

**Comment by myudelson** [comment]
Hello,
Thank you for reaching out.
Please compile the code first by running `make all` in the root folder of the repo. Depending on the OS you have you might have to install the make command. Refer to "Getting and Compiling the Code" section of the readme for that.
Best,
Michael

**Comment by manirds** [comment]
Thanks @myudelson for your prompt reply. 

I have two querries:

1. is there any sequence which need to be maintained for the training data as in by timestamp

my training data looks like this -- 

student1 --  timestamp1 -- question_attempted-1 -- response(1/2) -- skill name (abc)
student1 --  timestamp2 -- question_attempted-2 -- response(1/2) -- skill name (abc1)
student1 --  timestamp3-- question_attempted-3 -- response(1/2) -- skill name (abc2)
student1 --  timestamp4-- question_attempted-4 -- response(1/2) -- skill name (abc3)

should I sort it by student and timestamp or by (student and skill name)

Also can you please tell me how the train and test split is being done? As mentioned in the other issues discussed I can see you mentioned that the train test split is taken care inside the code itself (trainhmm.cpp).

2. When I am trying to train on my data my pl0 for all the skills is 0.5. I am using the below command for training.
./trainhmm -s 1.1 -m 1 -p 1 toy_data.txt model.txt predict.txt

Thanks in anticipation

**Comment by myudelson** [comment]
Hello,
My apologies for noticing your follow-up question so late.
The data should be sorted within student and within student skill. Across students and across skills, it does not have to be sorted.
And the columns should be: observation, student, item, skill(s).
Best,
Michael
