### ISSUE TITLE
training getting killed 

### ISSUE THREAD

**Issue by rajm23sc** [myudelson/hmm-scalable#6]
@myudelson, I have 30 million attempt rows, when I train using the setting -s 1.1 or -s 1.2 it's training on skill level, then can I make a partition of the whole data like each partition will have attempts of students on each skill. please do help

**Comment by myudelson** [comment]
Hello, are you using original code or forked code? Can you post your error message? 
The repo contains an Xcode project file so you could run the fit job in a debug mode and trace the error. Do you think you can do it?

**Comment by myudelson** [comment]
rajm23sc, were you able to curb the issue?
I'm guessing if you didn't write back it's gone and I can close this issue.
