### ISSUE TITLE
compile issue

### ISSUE THREAD

**Issue by Chungsoo86** [myudelson/hmm-scalable#7]
Hello, I hope you are doing well :).

I'm really new to the BKT field. I tried to compile your codes in cygwin and faced some errors.

HMMProblem.cpp:3181:11: error: ‘dt’ was not declared in this scope
 3181 |     data *dt = this->p->k_data[k];
      |           ^~
make: *** [makefile:62: HMMProblem.o] Error 1

Plus, I was able to notice that instead of creating "trainhmm" executable file, " "trainhmmst.exe" was generated. And I tried to execute the code "./trainhmm -s 1.1 -m 1 -p 1 toy_data.txt model.txt predict.txt", but I got the error message: "-bash: ./trainhmm: No such file or directory" 

I will be grateful if you give some guidance to solve the issues.

Thanks,

Best,
Chungsoo

**Comment by myudelson** [comment]
Chungsoo,
Thank you for noticing the bug. As I was using MacOS XCode, it might have been glancing over the problem that gcc/g++ doesn't auto-fix. I've made sure the struct data is handled properly. Now `make all` should build all executables.
Best,
Michael

**Comment by Chungsoo86** [comment]
Thanks for your prompt response! 
For some reason, I faced another bug while compiling your codes.

HMMProblem.cpp:3183:23: error: ‘dt’ was not declared in this scope; did you mean ‘tt’?
 3183 |     for(NDAT tt=0; tt<dt->n; tt++) {
      |                       ^~
      |                       tt
make: *** [makefile:62: HMMProblem.o] Error 1

could you check this one more time?

Thank you,

Best,
Chungsoo

**Comment by Chungsoo86** [comment]
Thank you so much for your prompt reply and it works! Once again, I really appreciate your help! :)

Best,
Chungsoo
